import ExcelJS from "exceljs";
import {
  IStudentRecord,
  ISubjectRecord,
  IRatingItem,
  IRating,
  IAffectiveDomain,
  IPsychomotorSkills,
} from "./build-student-sheet.js";

/**
 * Parses a student-record Excel file generated by `buildStudentSheet`
 * back into fully populated `IStudentRecord` objects.
 *
 * ✔ Extracts hidden immutable metadata
 * ✔ Reconstructs populated references
 * ✔ Guarantees non-empty identity fields
 * ✔ Strictly mirrors the builder layout
 *
 * @param buffer Raw Excel file buffer
 */
export async function parseStudentRecordExcelFile(
  buffer: Buffer
): Promise<IStudentRecord[]> {
  const workbook = new ExcelJS.Workbook();
  await workbook.xlsx.load(buffer);

  const records: IStudentRecord[] = [];

  /**
   * Locate a row by its first-cell label
   */
  const findRow = (sheet: ExcelJS.Worksheet, label: string): number => {
    let found = 0;
    sheet.eachRow((row, idx) => {
      if (row.getCell(1).text.trim() === label) {
        found = idx;
      }
    });
    return found;
  };

  workbook.worksheets.forEach((sheet) => {
    /* ============================================================
     * 1. HIDDEN SYSTEM METADATA (AUTHORITATIVE)
     * ============================================================ */
    const system: Record<string, string> = {};

    sheet.eachRow((row) => {
      const key = row.getCell(1).text.trim();
      if (key.startsWith("__")) {
        system[key] = row.getCell(2).text.trim();
      }
    });

    /* ============================================================
     * 2. INITIALIZE RECORD (FULLY STRUCTURED)
     * ============================================================ */
    const record: IStudentRecord = {
      _id: system["__recordId"] || "",
      business: system["__business"] || "",
      academicTerm: system["__academicTerm"] || "",
      studentId: {
        _id: system["__studentId"] || "",
        fullName: "",
        studentId: "",
      },
      classSection: {
        _id: system["__classSectionId"] || "",
        sectionName: "",
      },
      subjectRecords: [],
    };

    /* ============================================================
     * 3. SECTION 1: BASIC INFO (DISPLAY VALUES)
     * ============================================================ */
    sheet.eachRow((row) => {
      const label = row.getCell(1).text.trim();
      const value = row.getCell(2).text.trim();

      switch (label) {
        case "Student Name":
          record.studentId.fullName = value;
          break;
        case "Student ID":
          record.studentId.studentId = value;
          break;
        case "Class":
          record.classSection.sectionName = value;
          break;
      }
    });

    /**
     * Absolute safety fallback
     * (builder always sets these, but never trust files blindly)
     */
    if (!record.studentId.fullName) {
      record.studentId.fullName = sheet.name;
    }

    if (!record.studentId.studentId) {
      record.studentId.studentId = system["__studentId"] || "";
    }

    if (!record.classSection.sectionName) {
      record.classSection.sectionName = "UNKNOWN";
    }

    /* ============================================================
     * 4. SECTION 2: SUBJECT RECORDS
     * ============================================================ */
    const subjectHeaderRowIdx = findRow(sheet, "Subject");
    if (!subjectHeaderRowIdx) {
      throw new Error(`Invalid sheet "${sheet.name}": Subject table missing`);
    }

    const headerRow = sheet.getRow(subjectHeaderRowIdx);
   const scoreNames: string[] = [];
    for (let col = 2; col <= headerRow.cellCount - 3; col++) {
      const value = headerRow.getCell(col).text.trim();
      if (value) {
        scoreNames.push(value);
      }
    }

    for (
      let r = subjectHeaderRowIdx + 1;
      r <= sheet.rowCount;
      r++
    ) {
      const row = sheet.getRow(r);
      const subjectName = row.getCell(1).text.trim();
      if (!subjectName) break;

      const scores = scoreNames.map((name, i) => ({
        name,
        value: Number(row.getCell(2 + i).value ?? 0),
        maxValue: 100,
      }));

      record.subjectRecords.push({
        subjectName,
        scores,
        totalScore: Number(row.getCell(2 + scores.length).value ?? 0),
        grade: row.getCell(3 + scores.length).text.trim(),
        remark: row.getCell(4 + scores.length).text.trim(),
      });
    }

    /* ============================================================
     * 5. DOMAIN SECTIONS (AFFECTIVE / PSYCHOMOTOR)
     * ============================================================ */
    const parseDomain = (title: string): IRatingItem[] => {
      const items: IRatingItem[] = [];
      const sectionRow = findRow(sheet, title);
      if (!sectionRow) return items;

      const headerRow = sheet.getRow(sectionRow + 2);
      const ratingSlots = headerRow.cellCount - 2;

      for (let r = sectionRow + 3; r <= sheet.rowCount; r++) {
        const row = sheet.getRow(r);
        const label = row.getCell(1).text.trim();
        if (!label) break;

        const rating: IRating[] = [];

        for (let i = 0; i < ratingSlots; i++) {
          const checked = row.getCell(2 + i).value === true;
          rating.push({
            rate: i + 1,
            value: checked ? i + 1 : null,
          });
        }

        items.push({
          label,
          rating,
          remark: row.getCell(2 + ratingSlots).text || null,
        });
      }

      return items;
    };

    const affective = parseDomain("SECTION 3: AFFECTIVE DOMAIN");
    if (affective.length) {
      record.affectiveDomain = { items: affective } as IAffectiveDomain;
    }

    const psychomotor = parseDomain("SECTION 4: PSYCHOMOTOR SKILLS");
    if (psychomotor.length) {
      record.psychomotorSkills = {
        items: psychomotor,
      } as IPsychomotorSkills;
    }

    /* ============================================================
     * 6. COMMENTS & SIGNATURES
     * ============================================================ */
    sheet.eachRow((row) => {
      const label = row.getCell(1).text.trim();
      const value = row.getCell(2).text.trim();

      if (
        label === "Teacher Comment" ||
        label === "Head Teacher Comment"
      ) {
        record.commentsAndSignatures ??= {};
      }

      if (label === "Teacher Comment") {
        record.commentsAndSignatures!.teacherComment = value;
      }

      if (label === "Head Teacher Comment") {
        record.commentsAndSignatures!.headTeacherComment = value;
      }
    });

    records.push(record);
  });

  return records;
}
